script: bash ./deploy.sh
language: node_js
node_js:
  - '5'
env:
  global:
    - GH_REF: github.com/TondaHack/simplecalculation.git
    - secure: "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqbnvhNiwIEzvqfEfEk+9 p+yllteuTSAlK3Miq0rzxT0hkzEVGXVIaV0PqZ9YQaycFHk85FusPinnwPNfwAox ID3xYPx3gqeOgPb6b9fAHEv0tMPvDmZ9kShJbZaXMA+eoqxJ3L9yI6HkUh1Jkwpe 4x9k/VB+jHp1KFKSjfkUT2v4Mvc22ygW9lfjuajZ3pRvsKPgdbKjIXzlCiaU9P+t ngfLh8FqTYqsg7bZldf8P9rc/kIPIH0PVDwliXrYDO5aorkC7B3BCnhwF0KWTZ6o nLRT5wOF1GmZ2Jj9mLEVDHuLoW7SEiPCBqpKZkkrvY2LjQz8BNG3PGBRRulvODkz P7xPJFx4L2fVXXsRuKOyf0aVZd3MY72Jq63R28F/V4fLf9ZaA1kkxZF78KAQu0Du jIKtNUtGNBfaTs2kN0f+2A8xXyW8JdvgapPwoJTUb43Rgc7tdvGK9WdQmz8r+0CB Ohx2AtMpyF+WCeqSGeId1m8I0BcY1CJoiQNBysyNt5Lue1RAE90HVv1rIcmMa7A+ OW6z46UsKNERYU0Kl7cm4P2xSDNOFRG8kJkucLOl2xDDXNN9RXhuBXxt5Bhwg8ZT 1M5FyGB550Uk+Ban0ObkgooQOinHPZgxRfhnlHs+BepLWXF8vhAX/IbwCJFXuOnZ AxWOwMC/l0GkW54g/oQZPOcCAwEAAQ=="
branches:
  except:
    - gh-pages
  only:
    - master
