script: bash ./deploy.sh
language: node_js
node_js:
  - '5'
env:
  global:
    - GH_REF: github.com/TondaHack/simplecalculation.git
    - secure: "Gc93rOLNPIn6/b4p6m/Jy5cJGciMJhVZyT1HvNHDw5LfMvzon75D/VUN6gvBORogeEihUqM2BL/QdFqrlLnkiOmCN0ZDBemFNqGcgzxD2HBIXId52W4FNVegpHwFeqd1HkdZYqCb/ap8yWrlCmysWVk5JFzovCnd9MeiCuK+VokojhsGd2vEb6J9mm7TDq2TxqFz9YhoV5h4c/+DDJxVgL7WrVY3zm745O9h2DsXEZ+4N8ePdg1eB9FNJPWKqcH5KAqQiN3P6E+4YxGR7P9wa0HDR8iwoNbJcCEWf/0RlpvquPTpfoF1E7Hg9peIx4eg0bve5E8zFo3hB6BGfnXNUeqFd9XL2I5EmDGovrkGPvj6oONnATuFVBnvaO9uQz43NB+B6OpDVTf4mZ+05ieaQ3VOmQdH1CjsK21k82CM2PNWSh8/goyALS7JG6yWqDsAt9nKfzfVELNv6vSQrdHULxQCkL/8QHgEV8JUbUiBNllQwoExdIK5oK2v9CK76sUo4Mr1Y5BpEfi2QFEXJqbYslqr4E/S8DEsf36fm2pyS3Qk/MIxs+j8wkNmE2BKH/Ds2twW9BdWXlp014ncP0reBsjJQldOzH+M3j3qL8ZzzF3vTfFHQtj/evJaHMmvTSvyalvF/CTwg/n3w6vFoodjxoe3NQUgH7eiaLUtvMiVL2g="
branches:
  except:
    - gh-pages
  only:
    - master
